@api=http://localhost:5000

@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MTIyNTBkMjc0ZmM1MDFmMThjODY2ZTEiLCJuYW1lIjoiSm9obiBTbWl0aCIsImlhdCI6MTYyOTYzODg2NiwiZXhwIjoxNjI5NjQ2MDY2fQ.Ybb5H58QmpIDT9YBI2x1o9D-l77APADl43p_d2ypjwI

### Revalidate JWT
GET {{api}}/api/auth/renew
x-token: {{token}}

### Post login data
POST {{api}}/api/auth/
Content-Type: application/json

{
  "email": "email@email.com",
  "password": "1234567"
}

### Create new user
POST {{api}}/api/auth/new
Content-Type: application/json

{
  "name": "John Smith",
  "email": "email2@email.com",
  "password": "1234567"
}

### Get events
GET {{api}}/api/events
x-token: {{token}}


### Create a new event
POST {{api}}/api/events
x-token: {{token}}
Content-Type: application/json

{
  "title": "Cumple del jefe",
  "start": 1,
  "end": 1000000
}

### Update an event
PUT {{api}}/api/events/612259af429ed427d0192990
x-token: {{token}}
Content-Type: application/json

{
  "title": "Cumple del jefe",
  "notes": "Nota kul",
  "start": 1,
  "end": 1000000
}

### Delete an event
DELETE {{api}}/api/events/6122657ff8de280cf8767c28
x-token: {{token}}
