@api=http://localhost:5000

GET {{api}}/api/auth/renew

### Post login data
POST {{api}}/api/auth/
Content-Type: application/json

{
  "email": "email@email.com",
  "password": "1234567"
}

### Create new user
POST {{api}}/api/auth/new
Content-Type: application/json

{
  "name": "John Smith",
  "email": "email@email.com",
  "password": "1234567"
}